### ISSUE TITLE
Error in error handling if no IP address is found

### ISSUE THREAD

**Issue by stormi** [xenserver/xscontainer#56]
This line of code fails when executed, with message `AttributeError: 'module' object has no attribute 'ERROR_CAUSE_NETWORK'` https://github.com/xenserver/xscontainer/blob/master/src/xscontainer-prepare-vm#L80

See this bug reported by a user of XCP-ng, with full backtrace: https://github.com/xcp-ng/xcp/issues/198

I don't know the code of xscontainer enough to provide a patch, but the fix should be easy.

**Comment by stormi** [comment]
Ping?

**Comment by LunarstarFurry** [comment]
Meh Same here

**Comment by dalrrard** [comment]
Looks like this was introduced by commit 28142802a4049ae9cd45aaae65cb8e9a8692ed19 when they were separating out some functionality. I don't have time to test right now, but line 80 should probably be modified to be `print(remote_helper.ssh.ERROR_CAUSE_NETWORK)`
